### ISSUE TITLE
Decide on home/index page

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-portfolio#11]
Should the default page be projects, about, contact, resume or something else? Please share your thoughts.

**Comment by RFX14** [comment]
I was thinking the "about" just so that we can get an overview of a person. What ideas do y'all have?

**Comment by calvh** [comment]
Me personally I like to jump into code straightaway so I prefer to see the "projects" page.

**Comment by CaroCardozo** [comment]
I believe that the "about" maybe should be the main because I think like you first want to know who the person is and then what they have done
