### ISSUE TITLE
Rename index.html to base.html

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-portfolio#12]
I think we should rename `index.html` to `base.html` because its a template. I think of "index" as the homepage itself. What do you think?

**Comment by RFX14** [comment]
Would all of our pages be based off of this base.html template? Or only a few of the pages? Because if it won't be used for multiple pages as a template then I think it should stay as `index.html`

**Comment by calvh** [comment]
I think `base.html` should be the template to base everything off. I would then add, for example, Bootstrap tags there so I don't have to repeat that in all pages.

**Comment by RFX14** [comment]
So, then if we use a `base.html` then I guess we wouldn't need all of the different html files as we could just pass the needed information using Flask. Is that what you're ideally thinking then?

**Comment by calvh** [comment]
We could use a system like this:
(https://flask.palletsprojects.com/en/2.0.x/tutorial/templates/)

**Comment by RFX14** [comment]
Ah, alright that makes sense. I agree with changing `index.html` to `base.html`

**Comment by CaroCardozo** [comment]
A bit late, but I agree to having a template to be based on. It will make the things easier and faster

**Comment by calvh** [comment]
@RFX14 could you add this to PR #15?
